TARGETS = elastic_fp identical signed_elastic_fp boost_arbitrary_fp boost_arbitrary_fp_without_rep char_fp elastic_test elastic_fp_literal boost_arbitrary_fp_cast 

all: $(TARGETS)

CXXFLAGS += -I ../../include -g -fpermissive

clean:

	$(RM) $(TARGETS)
